In [1]:
# NumPy is a Python library used for working with arrays.
# It also has functions for working in domain of linear algebra, fourier transform, and matrices.
import numpy as np

In [2]:
a = [1, 2, 3, 4] # using variable
x = np.array([1, 2, 3, 4]) # without using variabl or Direct method
x

array([1, 2, 3, 4])

In [3]:
t = np.array(a)
t

array([1, 2, 3, 4])

In [4]:
y = (5, 6, 7, 8)# one dimentional array.
z = np.array(y)
z

array([5, 6, 7, 8])

In [5]:
x1 = [90, 30, True, 'Palle', 56+4j]
x1

[90, 30, True, 'Palle', (56+4j)]

In [6]:
# Here all elements change into string because array doesn't allow Hetrogeneous elemnts.
# priorites of aaray : Str -> complex -> float -> int-> boolean.
arr1 = np.array(x1)
arr1

array(['90', '30', 'True', 'Palle', '(56+4j)'], dtype='<U64')

In [7]:
# 2-D Arrays
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
z = [[1, 2, 3], [4, 5, 6]]
arr2d = np.array(z, ndmin = 3)
arr2d

array([[[1, 2, 3],
        [4, 5, 6]]])

In [8]:
# 3-D arrays
# its an combination of 2D array.
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [13]:
# Check Number of Dimensions?
# NumPy Arrays provides the 'ndim' attribute that returns an integer that tells us how many dimensions the array have.
# ndim -> will reflect dimention of an array.
zero = np.array(42)
one = np.array([1, 2, 3, 4, 5])
two = np.array([[1, 2, 3], [4, 5, 6]])
three = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print('Dimention of an array is', zero.ndim)
print('Dimention of an array is', one.ndim)
print('Dimention of an array is', two.ndim)
print('Dimention of an array is', three.ndim)

Dimention of an array is 0
Dimention of an array is 1
Dimention of an array is 2
Dimention of an array is 3


In [19]:
arr4 = np.arange(10) # 'arange' -> is just like range.
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr5 = np.arange(1, 10)
arr5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr6 = np.arange(1, 10, 2)
arr6

array([1, 3, 5, 7, 9])

In [24]:
# it will generate linerally spaced 50 elements between 2-3.
arr8 = np.linspace(2, 3)
arr8

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [25]:
arr9 = np.linspace(2, 3, 10)
arr9

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [27]:
arr10 = np.random.rand() # 'rand' -> It will reflect any random number.
arr10

0.34274503787436383

In [28]:
arr11 = np.random.rand(2, 5) # It will reflect random two rows and 5 columns.
arr11

array([[0.42310769, 0.18354419, 0.76432236, 0.75952152, 0.11257651],
       [0.34375486, 0.57422752, 0.54046438, 0.43494362, 0.60537103]])

In [31]:
arr12 = np.random.rand(4, 6) # It will reflect random 4 rows and 6 columns.
arr12

array([[0.76155028, 0.69864807, 0.52689967, 0.64362244, 0.0369283 ,
        0.31742267],
       [0.75979113, 0.51920902, 0.85588461, 0.01575525, 0.91121373,
        0.76343859],
       [0.01853349, 0.06316161, 0.2877656 , 0.15023491, 0.06460982,
        0.55912611],
       [0.74649277, 0.08064153, 0.71964245, 0.62416456, 0.82706999,
        0.82785846]])

In [33]:
arr13 = np.random.randint(1, 5) # randint -> it will generate one random number.
arr13

4

In [35]:
arr13a = np.random.randint(1, 5, 3)
arr13a

array([3, 1, 1])

In [36]:
arr13b = np.random.randint(1, 20, 10) # It will generate 10 elements of range of 1 to 20.
arr13b

array([16,  5,  7, 10, 18,  3,  7, 15, 19, 12])

In [37]:
x5 = np.arange(4).reshape(2, 2)
x5

array([[0, 1],
       [2, 3]])

In [55]:
x7 = np.arange(20).reshape(5, 4)
x7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [56]:
x7[1:3, 1:3] # array slicing technique.

array([[ 5,  6],
       [ 9, 10]])

In [50]:
x8 = np.random.randint(1, 50, 20).reshape(4, 5)
x8

array([[ 7, 22, 13, 24,  4],
       [35,  2, 19, 17, 23],
       [ 3, 34, 18, 32,  1],
       [40, 45, 24, 31, 31]])

In [53]:
x9 = np.linspace(1, 50, 20).reshape(4, 5)
x9

array([[ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947],
       [13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632],
       [26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316],
       [39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ]])

In [54]:
x8[2][2] # this will use for accesing index postion of array.

18