In [1]:
import numpy as np

In [2]:
arr = np.arange(21, 81).reshape(3, 4, 5)
arr

array([[[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]],

       [[61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70],
        [71, 72, 73, 74, 75],
        [76, 77, 78, 79, 80]]])

In [3]:
#1. Access only 1st row of each matrix.
arr[:, [0]]

array([[[21, 22, 23, 24, 25]],

       [[41, 42, 43, 44, 45]],

       [[61, 62, 63, 64, 65]]])

In [4]:
#2. Access only 2nd column of each matrix.
arr[0 : 3, 0:, 1]

array([[22, 27, 32, 37],
       [42, 47, 52, 57],
       [62, 67, 72, 77]])

In [7]:
#2.(another method) Access only 2nd column of each matrix.
arr[ :, :, 1:2]

array([[[22],
        [27],
        [32],
        [37]],

       [[42],
        [47],
        [52],
        [57]],

       [[62],
        [67],
        [72],
        [77]]])

In [5]:
#3. Access only 1st 3 column and all rows of 1st and 3rd matrix.
arr[0:3:2, 0:4, 0:3]

array([[[21, 22, 23],
        [26, 27, 28],
        [31, 32, 33],
        [36, 37, 38]],

       [[61, 62, 63],
        [66, 67, 68],
        [71, 72, 73],
        [76, 77, 78]]])

In [6]:
#4. Access only 2nd and 3rd rows with all column of 2nd and 3rd matrix.
arr[1:3, 1:3, 0:5]

array([[[46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55]],

       [[66, 67, 68, 69, 70],
        [71, 72, 73, 74, 75]]])