In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 50, 20).reshape(5, 4)
arr

array([[47, 48, 43, 48],
       [ 6, 22, 17, 28],
       [40, 14, 15, 19],
       [13, 19, 35, 12],
       [10,  4, 31, 16]])

In [3]:
# Apply for loop for accessing every element of the array.
for i in arr:
    print(i)

[47 48 43 48]
[ 6 22 17 28]
[40 14 15 19]
[13 19 35 12]
[10  4 31 16]


In [4]:
# Find whether an array is having odd number or not.
countodd = 0
rows = len(arr)
cols = len(arr[0])
for i in range(0, rows):
    for j in range(0, cols):
        if(arr[i][j]%2 != 0):
            countodd = countodd + 1
print(countodd)

9


In [5]:
# Write a code to access 3d array by using loop.
arr1 = np.arange(20).reshape(2, 2, 5)
for i in range(len(arr1)):
    for j in range(len(arr1[i])):
        print(arr1[i][j])


[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [6]:
# Write a logic to get sum of the elements of an array.
def _sum(arr1):
    sum = 0
    for i in arr1:
        sumi = sum + 1
    for j in arr1:
        sumj = sum + 1
    for k in arr1:
        sumk = sum + 1
    result = sumi + sumj + sumk
    return(result)

n = len(arr1)
ans = _sum(arr1)
print("sum of an aaray's elements is", ans)
# not getting right vlaue using this logic so used predifined function 'sum'.

sum of an aaray's elements is 3


In [7]:
sum_of_elements = np.sum(arr)
sum_of_elements

487